### ISSUE TITLE
README for the deployment folder

### ISSUE THREAD

**Issue by cristianpjensen** [cristianpjensen/Stock-Market-Prediction-via-Google-Trends#58]
The deployment needs to be shown via GIFs. No one will open the `index.html` in a live server. This is the easiest/best way to show it.

**Comment by imanishbarnwal** [comment]
Hello @cristianpjensen, can I take this issue?

**Comment by cristianpjensen** [comment]
@imanishbarnwal Sure!

**Comment by imanishbarnwal** [comment]
> @imanishbarnwal Sure!

So, I have to make a gif and update it to README.md ??? Or somewhere else let me know.

**Comment by cristianpjensen** [comment]
> So, I have to make a gif and update it to README.md ??? Or somewhere else let me know.

In the `deployment`-folder, I would like a README.md. This README.md should contain GIFs from the `index.html`. The way you can see the web page is by using a live server (you can find [an extension[(https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) in VSCode). 

So you have to download the deployment folder and open `index.html` with a live server. I would prefer safari, since some things only work in safari, and it looks better there. Then I would like for you to write a README.md, which contains GIFs from the webpage.

If you don't know what to write about, just ask me what I want it to contain.

GIFs over the entire webpage and over some of the "bigger" features is preferable.
